### ISSUE TITLE
Sign Language Prediction

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#14]
Hey LGM-SoC participants, good to see you.

With this project, you should be able to predict the sign language using hand gestures.

Dataset : https://www.kaggle.com/datamunge/sign-language-mnist

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.

Enjoy your open source journey!😎

**Comment by Anshal55** [comment]
---
Title: Sign Language Prediction
About: This project could have a lot of uses such as helping ease the communication with people who don't know sign language.
Name: Anshal Singh
Label: Feature Request

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor




**Is your feature request related to a problem? Please describe.**



**Describe the solution you'd like...**
I want to build a model and back  end for this project so that the results can be obtained after uploading images.

**Comment by Anshal55** [comment]
Also can I pick my own issue to work on after this?

**Comment by prathimacode-hub** [comment]
Yeah, sure. So you want to work on this issue first? You can take up your own issue as well. No restrictions on that. That's great. What would you use to make this model work efficiently? @Anshal55

**Comment by Anshal55** [comment]
Yeah I have the code for this just have to deploy I'll do this then create a new issue if that's okay?
To make this efficient I'll try to implement as simple model first then go from there depending upon the results.
@prathimacode-hub

**Comment by prathimacode-hub** [comment]
Yes, it's absolutely okay. Sure, you can proceed. I had assigned this issue to you. For now, I will add it as Model Creation. @Anshal55
