### ISSUE TITLE
Stress Level Prediction

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#15]
Hey LGM-SoC participants, good to see you.

This project should help you in predicting your stress level.

Dataset : https://www.kaggle.com/shivamb/ideal-student-life-survey

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.

Enjoy your open source journey!😎

**Comment by jayant766** [comment]
please assign it to me under LGM-SOC'21

**Comment by ayushi424** [comment]
hey @prathimacode-hub ,
I would like to work on this issue, mainly model creation.
I'll proceed by data exploration to find any null values and if present then clean the data.
Then find what features/ factors result in more stress level, and then create model using more than 1 algorithm and evaluate which algorithm turns out to be the best.
Please assign.

**Comment by prathimacode-hub** [comment]
Sure, this issue is assigned to you. You can proceed. @ayushi424

**Comment by prathimacode-hub** [comment]
@jayant766, you had expressed your interest for other issue as well. Kindly let me know if you would like to work on that issue?

**Comment by jayant766** [comment]
@prathimacode-hub yes I want to work on that issue
