### ISSUE TITLE
Youtube Video Recommendation Systems

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#246]
Hey LGM-SoC participants, good to see you.

This project would suggest you with recommendations on youtube taking up the input of previous search results.

You can take up your own public dataset.

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can focus on providing an efficient solution.

Enjoy your open source journey!😎

**Comment by Akash20x** [comment]
I would like to work on this issue under LGM-SOC'21

**Comment by Akash20x** [comment]
@prathimacode-hub
I would like to work on this issue as a part of LGM-SOC'21.

I want to work on the model creation. In this user will give search query and it will predict different titles of the videos for that query.

Since I didn't find any relevant dataset related to this issue, so I will make a dataset using YouTube data api which has columns like Video Id,Description,Category and Title.

Categories involved Education, Food Music, Arts, Science & Technology and Gaming. 

I will use 3 models KNN, TfidfVectorizer and Doc2vec and compare these models and check which give best prediction.

**Comment by prathimacode-hub** [comment]
That sounds awesome, Make sure you add up your dataset in "Dataset" Folder and follow the contributing guidelines and project structure given. Issus is assigned to you. @Akash20x
