### ISSUE TITLE
Insurance Claim Prediction

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#253]
Hey LGM-SoC participants, good to see you.

Insurance claim prediction will help us in predicting whether we would attain insurance claim or not based on dataset provided. 

Dataset : https://www.kaggle.com/easonlai/sample-insurance-claim-prediction-dataset

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.

Enjoy your open source journey!😎

**Comment by ayushi424** [comment]
hey @prathimacode-hub ,
I'd like to work on this issue.
Mainly on model creation part.
I'll proceed by data exploration, data cleaning(if required ), data visualization, model creation using different algorithms and lastly performance check to find which algorithm works best.
Since the target column has binary values, 0 and 1, I'll use different classification algorithms to classify if the user will  attain insurance claim or not.
please assign.

**Comment by prathimacode-hub** [comment]
Sure, go ahead. @ayushi424
