### ISSUE TITLE
COVID-19 ANALYSIS USING ML

### ISSUE THREAD

**Issue by SuryanshNaugraiya** [prathimacode-hub/ML-ProjectKart#307]
Define You:

- [x] LGM-SOC'21 Participant
- [ ] DevIncept Participant 
- [ ] Contributor

**Is your feature request related to a problem? Please describe.**
No, I have an amazing idea of the project **COVID-19 ANALYSIS USING ML**, it would be an end to end project

It would have 3 features:
1. **GLOBAL** this describes the destruction it has caused in any country.
2. **SYMPTOMS** this describes the common symptoms of covid-19, to aware the users.
3. **HISTORY** this describes that till date what is its effect in a particular country.
**Describe the solution you'd like...**
I want to develop a live web app. I have attached the required screenshots of its design.

![Screenshot (245)](https://user-images.githubusercontent.com/53707393/124350567-00bfef00-dc13-11eb-931e-135e28466c43.png)
![Screenshot (246)](https://user-images.githubusercontent.com/53707393/124350576-03224900-dc13-11eb-9682-9e7a0c14b2f2.png)
![Screenshot (247)](https://user-images.githubusercontent.com/53707393/124350579-04ec0c80-dc13-11eb-9c03-5afdeff7c780.png)
![Screenshot (248)](https://user-images.githubusercontent.com/53707393/124350582-06b5d000-dc13-11eb-8bb3-823ed255324b.png)
![Screenshot (249)](https://user-images.githubusercontent.com/53707393/124350584-087f9380-dc13-11eb-9075-16fbe1e6d49d.png)
![Screenshot (250)](https://user-images.githubusercontent.com/53707393/124350585-0a495700-dc13-11eb-8c35-e7a774ad4b47.png)
![Screenshot (251)](https://user-images.githubusercontent.com/53707393/124350587-0ae1ed80-dc13-11eb-8800-8f18c87e1004.png)
![Screenshot (252)](https://user-images.githubusercontent.com/53707393/124350588-0b7a8400-dc13-11eb-8b7f-6a8f47bbd382.png)
![Screenshot (253)](https://user-images.githubusercontent.com/53707393/124350590-0cabb100-dc13-11eb-903d-53a1d9652f99.png)

**Describe alternatives you've considered?**

**Approach to be followed (optional):**

**Additional context**

**Comment by prathimacode-hub** [comment]
That's great initiative taken up from you. You can follow up for the issue here. #95 and get it assigned. But before that do the changes for your earlier PR. @SuryanshNaugraiya

**Comment by prathimacode-hub** [comment]
Sure, this issue is assigned. You can put up your project [here](https://github.com/prathimacode-hub/ML-ProjectKart/tree/main/Covid-19%20Data%20Analysis). Give the project folder title as "Your Full Name". Kindly follow the project structure like you did for early PR. @SuryanshNaugraiya

**Comment by prathimacode-hub** [comment]
This issue is again open for contributions. These are the datasets to follow. You can choose either of one and provide your analysis.

Dataset 1 : https://www.kaggle.com/allen-institute-for-ai/CORD-19-research-challenge (or)

Dataset 2 : https://www.kaggle.com/imdevskp/corona-virus-report (or)

Dataset 3 : https://www.kaggle.com/sudalairajkumar/novel-corona-virus-2019-dataset

By the way, I had created a new repo of Covid-19 Data Analysis. In this [repo](https://github.com/prathimacode-hub/ML-ProjectKart/tree/main/Covid-19%20Data%20Analysis), you can add up your "Full Name" as your folder title. Inside that, you can follow the project structure as usual. So that, mulitple persons can work on this issue, and their way of analysis can be differentiated by their names. @SuryanshNaugraiya

**Comment by harshita9621** [comment]
@prathimacode-hub Can I work on this issue under DevIncept21

**Comment by prathimacode-hub** [comment]
HYou had already worked on this earlier I guess. @harshita9621
