### ISSUE TITLE
Netflix EDA and Genre Prediction

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/ML-ProjectKart#350]
Hey LGM-SoC participants, good to see you.

This project will help us in exploring the data analysis and predicting the genres of the netflix shows using the given dataset. 

Dataset : https://www.kaggle.com/yogithasatyasri/netflix-shows-exploratory-analysis

If you like to work on this issue, follow the given guidelines for code as well as for the README. You can try to compare it using different algorithms.

**Comment by shivani6320** [comment]
I would like to contribute on this issue. I will perform a detailed EDA with visualizations and compare various models for prediction.
Please assign me this issue.

**Comment by prathimacode-hub** [comment]
Sure, issue assigned. @shivani6320

**Comment by shivani6320** [comment]
Hey @prathimacode-hub . I am done with the EDA part, but for genre prediction- its difficult to build better performance for predicting genre from the given data, because genre is least related to the other columns into dataset. I already tried different scaling methods with almost all classification models but couldn't reach accuracy higher than 45%.  It just shows that movie's genre can't be predicted from columns like title, director, cast, country or release year -it solely depends on content right?(Well that's my practical view, otherwise we need very large dataset for that kind of prediction)

      Here is my counter approach :  I have already done detailed analysis on data and gained insights. How about I better build a Netflix Movie Recommendation System which can be at least useful in a practical way rather than just predicting Genre of any Movie. Please let me know, what you think about it. I want to get work done on this issue and get it's PR merged before 10 july.

**Comment by prathimacode-hub** [comment]
Yup, Got your point. You can proceed. Change the issue title accordingly and also you're free to choose your own dataset, if this dataset doesn't work for you. Sure. @shivani6320
